#!/usr/bin/env bash
set -xeuo pipefail

cfssl gencert -initca ca.json | cfssljson -bare ca
cfssl gencert -ca ca.pem -ca-key ca-key.pem -config cfssl.json -profile server server.json | cfssljson -bare server
cat server.pem ca.pem >bundle.pem
