FROM python:3-alpine

COPY --from=builder /go/src/github.com/puppetlabs/nebula-tasks/__OUTPUTBIN__ /usr/bin/__OUTPUTBIN__
COPY --from=builder /go/src/github.com/puppetlabs/nebula-tasks/ni /usr/bin/ni

RUN apk --no-cache add bash ca-certificates git jq openssh && update-ca-certificates
RUN pip install awscli

COPY ./cmd/nebula-s3-uploader/content /nebula

WORKDIR /nebula
ENTRYPOINT ["/nebula/run.sh"]
