FROM alpine/helm:2.13.1

COPY --from=builder /go/src/github.com/puppetlabs/nebula-tasks/__OUTPUTBIN__ /usr/bin/__OUTPUTBIN__
COPY --from=builder /go/src/github.com/puppetlabs/nebula-tasks/ni /usr/bin/ni
RUN apk update && apk --no-cache add git gcc bind-dev musl-dev ca-certificates curl jq openssh openssl && update-ca-certificates

COPY ./cmd/nebula-helm-deployer/content /nebula

WORKDIR /nebula
ENTRYPOINT ["/nebula/run.sh"]