// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/puppetlabs/leg/vaultutil/pkg/vault"
	"github.com/puppetlabs/relay-core/pkg/install/op/kube"
	vault3 "github.com/puppetlabs/relay-core/pkg/install/op/vault"
	vault2 "github.com/puppetlabs/relay-core/pkg/install/vault"
)

import (
	_ "k8s.io/client-go/plugin/pkg/client/auth"
)

// Injectors from wire.go:

func NewVaultInitializer(ctx context.Context, vaultConfig *vault.VaultConfig, vaultCoreConfig *vault2.VaultCoreConfig) (*vault2.VaultInitializer, error) {
	config := vaultConfigMapper(vaultConfig)
	client, err := vault3.NewClient(ctx, config)
	if err != nil {
		return nil, err
	}
	scheme := kube.NewKubeScheme()
	clientClient, err := kube.NewKubeClient(scheme)
	if err != nil {
		return nil, err
	}
	vaultSystemManager := vault.NewVaultSystemManager(client, clientClient, vaultConfig)
	vaultInitializationManager := vault.NewVaultInitializationManager(vaultSystemManager, vaultConfig)
	vaultInitializer := vault2.NewVaultInitializer(vaultConfig, vaultCoreConfig, vaultInitializationManager, vaultSystemManager)
	return vaultInitializer, nil
}

// wire.go:

func vaultConfigMapper(vaultConfig *vault.VaultConfig) vault3.Config {
	return vault3.Config{
		Addr: vaultConfig.VaultAddr.String(),
	}
}
