// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/puppetlabs/leg/vaultutil/pkg/vault"
	vault2 "github.com/puppetlabs/relay-core/pkg/install/op/vault"
)

import (
	_ "k8s.io/client-go/plugin/pkg/client/auth"
)

// Injectors from wire.go:

func InitializeServices(ctx context.Context, cfg *vault.VaultConfig) (services, error) {
	config := vaultConfig(cfg)
	client, err := vault2.NewClient(ctx, config)
	if err != nil {
		return services{}, err
	}
	mainServices := services{
		vault: client,
	}
	return mainServices, nil
}

// wire.go:

func vaultConfig(cfg *vault.VaultConfig) vault2.Config {
	return vault2.Config{
		Addr: cfg.VaultAddr.String(),
	}
}
