FROM alpine:latest

COPY --from=builder /go/src/github.com/puppetlabs/nebula-tasks/__OUTPUTBIN__ /usr/bin/__OUTPUTBIN__
COPY --from=builder /go/src/github.com/puppetlabs/nebula-tasks/ni /usr/bin/ni

RUN apk --no-cache add bash ca-certificates curl jq xmlstarlet && update-ca-certificates

COPY ./cmd/nebula-jenkins-job-runner/content /nebula

WORKDIR /nebula
ENTRYPOINT ["/nebula/run.sh"]
