#!/usr/bin/env bash
set -euo pipefail

# this ensures that we are in the correct directory context
cd "$(dirname "$0")"/..

RELAY_CORE_REPO_BASE="${RELAY_CORE_REPO_BASE:-gcr.io/nebula-235818}"

for TARGET in relay-operator relay-metadata-api relay-metrics relay-runtime-tools; do
  (
    set -x
    docker build \
      -f "./cmd/${TARGET}/Dockerfile" \
      -t "${RELAY_CORE_REPO_BASE}/${TARGET}:${VERSION}" \
      .
  )
done
