#!/usr/bin/env bash
set -euo pipefail

if [ -z "${RELAY_EMAIL:-}" ] || [ -z "${RELAY_PASSWORD:-}" ] || [ -z "${RELAY_WORKFLOW:-}" ] || [ -z "${VERSION:-}" ] || [ "${NO_DOCKER_PUSH:-}" == "yes" ]; then
    echo "Branch ${TRAVIS_BRANCH} has no workflow configuration. Skipping deploy."
    exit 0
fi

CLI_VERSION="$( curl -s -I https://github.com/puppetlabs/relay/releases/latest | awk 'tolower($1) == "location:" { printf("%s", gensub(/.*\/(.*)\r/, "\\1", "g")) }' )"
mkdir -p .deploy
curl -LJ -o .deploy/relay \
    -H 'Accept: application/octet-stream' \
    "https://github.com/puppetlabs/relay/releases/download/${CLI_VERSION}/relay-${CLI_VERSION}-linux-amd64"
chmod +x .deploy/relay

mkdir -p ~/.config/relay

cat << EOF > ~/.config/relay/config.yaml
contexts:
  staging:
    apiDomain: https://api.stage.relay-infra.net
    uiDomain: https://ui.stage.relay-infra.net
EOF

.deploy/relay context set staging
echo -n "${RELAY_OPERATIONS_API_TOKEN}" | .deploy/relay auth login --stdin

echo -n "${VERSION}" | .deploy/relay workflow secret set "${RELAY_WORKFLOW}" tasks.image.tag --value-stdin
.deploy/relay workflow run "${RELAY_WORKFLOW}"
