#!/usr/bin/env bash
set -euo pipefail

if [ -z "${RELAY_EMAIL:-}" ] || [ -z "${RELAY_PASSWORD:-}" ] || [ -z "${RELAY_WORKFLOW:-}" ] || [ -z "${VERSION:-}" ] || [ "${NO_DOCKER_PUSH:-}" == "yes" ]; then
    echo "Branch ${TRAVIS_BRANCH} has no workflow configuration. Skipping deploy."
    exit 0
fi

mkdir -p .deploy
curl -LJ -o .deploy/relay \
    -H 'Accept: application/octet-stream' \
    "https://github.com/puppetlabs/relay/releases/download/v3.4.0/nebula-v3.4.0-linux-amd64"
chmod +x .deploy/relay

mkdir -p ~/.config/nebula
echo 'apiHostAddr: https://api.stage.relay-infra.net' >~/.config/nebula/config.yaml

echo -n "${RELAY_PASSWORD}" | .deploy/relay login -e "${RELAY_EMAIL}" -p
echo -n "${VERSION}" | .deploy/relay secret set -w "${RELAY_WORKFLOW}" -k tasks.image.tag -v
echo -n "${VERSION}" | .deploy/relay secret set -w "${RELAY_WORKFLOW}" -k metrics.image.tag -v
.deploy/relay workflow run -n "${RELAY_WORKFLOW}"
