FROM alpine:latest
COPY --from=builder /go/src/github.com/puppetlabs/nebula-tasks/__OUTPUTBIN__ /usr/bin/__OUTPUTBIN__
RUN apk update && apk --no-cache add git gcc bind-dev musl-dev ca-certificates && update-ca-certificates
CMD ["__DOCKER_CMD__"]
