#!/usr/bin/env bash
set -euo pipefail

NEBULA_TASKS_REPO_BASE="${NEBULA_TASKS_REPO_BASE:-gcr.io/nebula-235818}"
NEBULA_TASKS_RELEASE_REPOS=( "${NEBULA_TASKS_REPO_BASE}/relay-operator" "${NEBULA_TASKS_REPO_BASE}/relay-metadata-api" )

release_docker_images() {
    if [ "${NO_DOCKER_PUSH}" != "yes" ]; then
        gcloud auth configure-docker || fail "gcloud authentication was not configured correctly"

        for REPO in "${NEBULA_TASKS_RELEASE_REPOS[@]}"; do
            docker push "${REPO}:${VERSION}" || fail "failed to push to the docker repository"
            if [ "${NEBULA_TASKS_RELEASE_LATEST}" = "true" ]; then
                docker tag "${REPO}:${VERSION}" "${REPO}"
                docker push "${REPO}" || fail "failed to push to the docker repository"
            fi
        done
    else
        echo "docker images were created, but not pushed"
    fi
}

release_docker_images
