#!/usr/bin/env bash
set -euo pipefail

# this ensures that we are in the correct directory context
cd "$(dirname "$0")"/..

GO_TEST_ARGS=( -race )

if ! command -v gotestsum >/dev/null 2>&1; then
  go test "${GO_TEST_ARGS[@]}" ./...
else
  gotestsum -f testname --no-summary output --rerun-fails --packages ./... -- "${GO_TEST_ARGS[@]}"
fi
