//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionWebhookServerConfig) DeepCopyInto(out *AdmissionWebhookServerConfig) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionWebhookServerConfig.
func (in *AdmissionWebhookServerConfig) DeepCopy() *AdmissionWebhookServerConfig {
	if in == nil {
		return nil
	}
	out := new(AdmissionWebhookServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTSigningKeySource) DeepCopyInto(out *JWTSigningKeySource) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTSigningKeySource.
func (in *JWTSigningKeySource) DeepCopy() *JWTSigningKeySource {
	if in == nil {
		return nil
	}
	out := new(JWTSigningKeySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogServiceConfig) DeepCopyInto(out *LogServiceConfig) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialsSecretKeyRef != nil {
		in, out := &in.CredentialsSecretKeyRef, &out.CredentialsSecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogServiceConfig.
func (in *LogServiceConfig) DeepCopy() *LogServiceConfig {
	if in == nil {
		return nil
	}
	out := new(LogServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataAPIConfig) DeepCopyInto(out *MetadataAPIConfig) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSSecretName != nil {
		in, out := &in.TLSSecretName, &out.TLSSecretName
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.LogServiceURL != nil {
		in, out := &in.LogServiceURL, &out.LogServiceURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataAPIConfig.
func (in *MetadataAPIConfig) DeepCopy() *MetadataAPIConfig {
	if in == nil {
		return nil
	}
	out := new(MetadataAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorConfig) DeepCopyInto(out *OperatorConfig) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TenantSandboxingRuntimeClassName != nil {
		in, out := &in.TenantSandboxingRuntimeClassName, &out.TenantSandboxingRuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageAddr != nil {
		in, out := &in.StorageAddr, &out.StorageAddr
		*out = new(string)
		**out = **in
	}
	if in.TenantNamespace != nil {
		in, out := &in.TenantNamespace, &out.TenantNamespace
		*out = new(string)
		**out = **in
	}
	if in.LogStoragePVCName != nil {
		in, out := &in.LogStoragePVCName, &out.LogStoragePVCName
		*out = new(string)
		**out = **in
	}
	if in.ToolInjection != nil {
		in, out := &in.ToolInjection, &out.ToolInjection
		*out = new(ToolInjectionConfig)
		**out = **in
	}
	if in.AdmissionWebhookServer != nil {
		in, out := &in.AdmissionWebhookServer, &out.AdmissionWebhookServer
		*out = new(AdmissionWebhookServerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorConfig.
func (in *OperatorConfig) DeepCopy() *OperatorConfig {
	if in == nil {
		return nil
	}
	out := new(OperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelayCore) DeepCopyInto(out *RelayCore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelayCore.
func (in *RelayCore) DeepCopy() *RelayCore {
	if in == nil {
		return nil
	}
	out := new(RelayCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RelayCore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelayCoreList) DeepCopyInto(out *RelayCoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RelayCore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelayCoreList.
func (in *RelayCoreList) DeepCopy() *RelayCoreList {
	if in == nil {
		return nil
	}
	out := new(RelayCoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RelayCoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelayCoreSpec) DeepCopyInto(out *RelayCoreSpec) {
	*out = *in
	if in.JWTSigningKeyRef != nil {
		in, out := &in.JWTSigningKeyRef, &out.JWTSigningKeyRef
		*out = new(JWTSigningKeySource)
		**out = **in
	}
	if in.LogService != nil {
		in, out := &in.LogService, &out.LogService
		*out = new(LogServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Operator.DeepCopyInto(&out.Operator)
	in.MetadataAPI.DeepCopyInto(&out.MetadataAPI)
	in.Vault.DeepCopyInto(&out.Vault)
	if in.SentryDSNSecretName != nil {
		in, out := &in.SentryDSNSecretName, &out.SentryDSNSecretName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelayCoreSpec.
func (in *RelayCoreSpec) DeepCopy() *RelayCoreSpec {
	if in == nil {
		return nil
	}
	out := new(RelayCoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolInjectionConfig) DeepCopyInto(out *ToolInjectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolInjectionConfig.
func (in *ToolInjectionConfig) DeepCopy() *ToolInjectionConfig {
	if in == nil {
		return nil
	}
	out := new(ToolInjectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuthConfig) DeepCopyInto(out *VaultAuthConfig) {
	*out = *in
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(VaultAuthData)
		(*in).DeepCopyInto(*out)
	}
	if in.UnsealKey != nil {
		in, out := &in.UnsealKey, &out.UnsealKey
		*out = new(VaultAuthData)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuthConfig.
func (in *VaultAuthConfig) DeepCopy() *VaultAuthConfig {
	if in == nil {
		return nil
	}
	out := new(VaultAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuthData) DeepCopyInto(out *VaultAuthData) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(VaultAuthSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuthData.
func (in *VaultAuthData) DeepCopy() *VaultAuthData {
	if in == nil {
		return nil
	}
	out := new(VaultAuthData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuthSource) DeepCopyInto(out *VaultAuthSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuthSource.
func (in *VaultAuthSource) DeepCopy() *VaultAuthSource {
	if in == nil {
		return nil
	}
	out := new(VaultAuthSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultConfig) DeepCopyInto(out *VaultConfig) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(VaultAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	out.Engine = in.Engine
	in.Server.DeepCopyInto(&out.Server)
	in.Sidecar.DeepCopyInto(&out.Sidecar)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultConfig.
func (in *VaultConfig) DeepCopy() *VaultConfig {
	if in == nil {
		return nil
	}
	out := new(VaultConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultEngineConfig) DeepCopyInto(out *VaultEngineConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultEngineConfig.
func (in *VaultEngineConfig) DeepCopy() *VaultEngineConfig {
	if in == nil {
		return nil
	}
	out := new(VaultEngineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultServerBuiltInConfig) DeepCopyInto(out *VaultServerBuiltInConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.ConfigMapRef = in.ConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultServerBuiltInConfig.
func (in *VaultServerBuiltInConfig) DeepCopy() *VaultServerBuiltInConfig {
	if in == nil {
		return nil
	}
	out := new(VaultServerBuiltInConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultServerConfig) DeepCopyInto(out *VaultServerConfig) {
	*out = *in
	if in.BuiltIn != nil {
		in, out := &in.BuiltIn, &out.BuiltIn
		*out = new(VaultServerBuiltInConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultServerConfig.
func (in *VaultServerConfig) DeepCopy() *VaultServerConfig {
	if in == nil {
		return nil
	}
	out := new(VaultServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSidecarConfig) DeepCopyInto(out *VaultSidecarConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSidecarConfig.
func (in *VaultSidecarConfig) DeepCopy() *VaultSidecarConfig {
	if in == nil {
		return nil
	}
	out := new(VaultSidecarConfig)
	in.DeepCopyInto(out)
	return out
}
